### ISSUE TITLE
Sendungen mit umlauten im Titel gehen nicht !?

### ISSUE THREAD

**Issue by connikullmann** [raptor2101/Mediathek#100]
Hi,

bei Sendungen mit Umlauten im Titel z.B. "Sträters Männerhaushalt" in der ARD, gibt es zwei Fehler ala:

                                           UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3
 in position 33: ordinal not in range(128) 

Wenn man in default.py Zeile 82
    # gui.log(link);
und in simplexbmc.py Zeile 45
   #xbmc.log("[%s]: %s" % (__plugin__, msg.encode('utf8')))

kommentiert, dann funktioniert's.
Wie sieht dazu ein "richtiger" Fix aus ?

Gruss
Stefan

**Comment by florianjacob** [comment]
Gleiches Problem hier mit „Verrücht nach Meer“

**Comment by florianjacob** [comment]
@raptor2101 funktioniert, vielen Dank! :sparkles: :ship: :anchor:

**Comment by connikullmann** [comment]
funktioniert, danke !
