### ISSUE TITLE
ARD Mediathek Lindenstraße

### ISSUE THREAD

**Issue by DedeUeha** [raptor2101/Mediathek#102]
Hallo.
Ich habe das Problem, dass bei mir das Abspielen der Serie "Lindenstraße" im Mediathek-Addon nicht funktioniert.
Dies ist umso verwunderlicher, da das Abspielen anderer Serien/Filme der ARD im Addon funktioniert.
Inwiefern unterscheidet sich die Lindenstrasse von anderen Serien/Filmen/Beiträgen?
Existieren lizenzrechtliche Unterschiede, die diese Ungleichbehandlung verursachen?

Ich benutze Krypton, und habe das Addon mit der Version 0.8.5 installiert.

Vielen Dank für Antworten / Ideen...

**Comment by raptor2101** [comment]
Aktiv macht das addon da nichts um den inhalt zu blocken. Kannst du mal ein Log vom Abspielversuch posten?

**Comment by DedeUeha** [comment]
Hi. 
Danke für die schnelle Antwort.

Hatte irgendwie Probleme beim Erstellen des Logs.
Ich habe 'Settings/System Settings/Logging/Enable Debug Log' aktiviert.
'Settings/Libreelec/System/Pastebin system logs and get short URL' gibt mir eine Fehlermeldung zurück.
Lediglich mit dem 'Kodi Logfile Uploader'-Addon hat es dann funktioniert.
(Vll kannst du mir netterweise sagen, wie du deine Logs erstellst.)

Hier das erstellte Log: https://paste.ubuntu.com/26241853/.
Die geworfene Exception ist vom Typ 'UnicodeDecodeError'. 
Hat es möglicherweise etwas mit dem im Namen enthaltenen "ß" zu tun.

Besten Gruß

**Comment by florianjacob** [comment]
Trifft wohl auf alle Sendungen mit Umlauten zu, siehe https://github.com/raptor2101/Mediathek/issues/100

**Comment by raptor2101** [comment]
sollte gelöst sein bitte testen

**Comment by raptor2101** [comment]
da Lindenstraße nun abgesetzt ist ...
