### ISSUE TITLE
ZDF Mediathek incomplete?

### ISSUE THREAD

**Issue by m-reiter** [raptor2101/Mediathek#109]
I tried to watch this programme: https://www.zdf.de/dokumentation/iran-bittersuess---reise-durch-ein-land-der-widersprueche-100.html in Mediathekbut could not find it, neither by browsing through the categories nor via the search function (I tried "Iran" and "bittersüß").

Is the programme missing or am I just searching the wrong way?

**Comment by raptor2101** [comment]
you are right. ZDF doesn't supply there Show during the "initial JSONs"... i look into reimplement the search and switch back to "hard links"

**Comment by raptor2101** [comment]
Switching back to "hard links" would needs roll-back to the old "html based" scraping of the Mediathek. What is fare more unstable the current JSON based approach. Will look into "get the search working again"...

**Comment by raptor2101** [comment]
if pushed a change so the search function is available again. simply search after the title an the first entry is your show...

I will prepare a PR tomorrow
