### ISSUE TITLE
Ard gibt Fehler

### ISSUE THREAD

**Issue by MichaelHoppe** [raptor2101/Mediathek#110]
Wenn ich mich in Ard durch die Menüs clicke (zb Beliebte Serien oder Drama) bekomme ich folgenden Fehler

 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>                                            Error Contents: ('$ROOT_QUERY.widget({"client":"ard","pageNumber":0,"pageSize":24,"widgetId":"4uik1P7uJWCqmkiqkIqCmu"})',)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.mediathek/default.py", line 100, in <module>
                                                mediathek.buildJsonMenu(path,callhash,0)
                                              File "/storage/.kodi/addons/plugin.video.mediathek/mediathek/ard.py", line 109, in buildJsonMenu
                                                widgetContent = jsonContent[self.buildcategoryListingKey(client,widgetId,jsonContent)];
                                            KeyError: ('$ROOT_QUERY.widget({"client":"ard","pageNumber":0,"pageSize":24,"widgetId":"4uik1P7uJWCqmkiqkIqCmu"})',)
                                            -->End of Python script error report<-
19:46:55.037 T:1258288032   ERROR: GetDire
ctory - Error getting plugin://plugin.vide
o.mediathek/?type=ARD&action=openJsonPath&
path=ard.4uik1P7uJWCqmkiqkIqCmu&callhash=b
f3384e182653597d4cae3ee2f65a636

**Comment by raptor2101** [comment]
confirmed

**Comment by raptor2101** [comment]
how it seems, ARD anouncing empty categories. my script has to filter them....

**Comment by raptor2101** [comment]
ok now they use JS to load JSON "at runtime", i'am impressed...

**Comment by raptor2101** [comment]
@MichaelHoppe can you test the commit fe88b80

**Comment by raptor2101** [comment]
nope, i will track this with this bug...

thanks for your debugging. i will look into this this evening

**Comment by raptor2101** [comment]
Sorry ich blicke erst jetzt, dass du mich ja auf deutsch angeschrieben hast.

ich hab mir das mal angeschaut. Wie es aussieht, ist es "Work as Designed". Wenn ich den Link im Browser aufrufe, bekomme ich "Der Beitrag ist nicht vorhanden bzw. nicht mehr verfügbar."

Das Plugin sollte das Abfangen, aber ich kann nicht vorher Prüfen ob der Link einen gültigen VideoLink bereit hält (zu mindestens nicht ohne, dass ich alle links crawle, und das dauert leider...)

**Comment by raptor2101** [comment]
kannst du mal 2437ff0 ausprobieren...

**Comment by MichaelHoppe** [comment]
Ja, das funktioniert. Mit dem commit kommt der Fehler nicht mehr!
