### ISSUE TITLE
ARD loadings takes to long....

### ISSUE THREAD

**Issue by raptor2101** [raptor2101/Mediathek#21]

**Comment by prof-membrane** [comment]
The add-on is still spamming web pages. Please correct this.

**Comment by p-friedrich** [comment]
> The add-on is still spamming web pages. Please correct this.

@prof-membrane  Can you be a little more specific? The addon requests one HTML page for every submenu that is opened and parses the HTML to find any videolinks.

**Comment by prof-membrane** [comment]
It requests not just one HTML page if a video is present. It scrapes every video page for no valid reason. These calls are unnecessary. They cause a high server load and a long delay to view the actual page. This may trigger the DDOS prevention after a few page views and the user is left with a loading screen.

**Comment by raptor2101** [comment]
I'am unable to find the problem. I can't see where the plugin spamms page request. If  a site ofers links, the scrapper tries to load the pages, thats what's the user expect.

To mitigate the probleme, paging was introduced
