### ISSUE TITLE
ARTE (Themen -> Kino & Serien) in Mediathek (0.6.4) does not work with kodi 14.0 on windows

### ISSUE THREAD

**Issue by GitHubTW** [raptor2101/Mediathek#40]
Hallo raptor2101,

ich gehe davon aus, dass Du deutsch (mindestens) verstehst.

Erstmal VIELEN DANK für die Erstellung der Add-ons!!!

Wie oben schon geschrieben steht, funktioniert bei ARTE im Add-On Mediathek (0.6.4) der Zweig Themen -> Kino & Serien nicht (die anderen auch nicht). Kann man das "reparieren"?
 Es fehlt außerdem der Bereich Letze Chance!

Vorab schon mal VIELEN DANK für den Support!

Gruß
Thomas

**Comment by raptor2101** [comment]
ich schau mir das heute abend mal an

**Comment by raptor2101** [comment]
versuch mal bitte in der arte.py folgenden string "regions=ALL%2Cdefault%2CDE_FR%2CSAT%2CEUR_DE_FR" durch "regions=EUR_DE_FR%2CDE_FR%2CSAT%2CALL" zu ersetzten.

**Comment by GitHubTW** [comment]
Vielen Dank für die Rückmeldung! Sobald ich kann, werde ich das machen!

**Comment by GitHubTW** [comment]
Hallo!

Die Änderung oben habe ich nicht getestet. Aber ich habe nun auf meinem Raspberry openelec 5.0.0 und die Mediathek Version 0.6.5 installiert.

Der Zweig 'Themen -> Kino & Serien' funktioniert nun.
Allerdings auf wird beim addon Arte.tv Version 2.1.4 bei der Liste auch die Länge der Videos angezeigt. Das fehlt hier leider!!!


Die Zweige 'Meistgesehen' und 'Letzte Chance' fehlen leider immer noch!

DANKE!
