### ISSUE TITLE
NDR page navigation doesn't work (multipage)

### ISSUE THREAD

**Issue by uweschmeling** [raptor2101/Mediathek#42]
Hi again, 

the following replacement for page navigation solves the problem described above:
    #Pagination (weiter/zurück)
    regex_extractNextPage = re.compile("<a title=\"(.*?)\" href=\"(.*?)\" class=\"button iconbutton square\">")
    itemCount = 0
    for nextPageHref in regex_extractNextPage.finditer(htmlPage):
        menuItemName = nextPageHref.group(1).decode('UTF-8')
        link = self.rootLink+nextPageHref.group(2)
        itemCount = itemCount + 1
        self.gui.buildVideoLink(DisplayObject(menuItemName,"","","description",link,False),self,nodeCount+itemCount);

regards Uwe

**Comment by raptor2101** [comment]
will release a patch at the weekend
