### ISSUE TITLE
Change Logos

### ISSUE THREAD

**Issue by alpha-ninja** [raptor2101/Mediathek#44]
I made you a thing:

https://github.com/alpha-ninja/MediathekLogos/

If you'd like me to make any changes (or create more logos), just tell me. :smile:

**Comment by raptor2101** [comment]
Feel free to replace the files in the resources folder, do a change in the simplexbmc.py (listavailablemediathek) and make a pull request.

I'am currently looking into the reported bugs

**Comment by alpha-ninja** [comment]
Would you be ok if I create a link to the MediathekIcons/png folder and accordingly change the icon filenames in the python scripts? I feel this would be the better option... If you agree, I can add you to the MediathekIcons repo with full permissions (alternatively, you can add its contents here, although it might be nice to have it separate so we can continue to keep the svgs without increasing the addon's size...)

BTW: Should I add a background color to the icons? If so, what color?

**Comment by raptor2101** [comment]
the addon-repo will make one pull to, so the images has to to be part of the given github-repo. how you organise the sub-folders, doesn't matter to me ;)

**Comment by alpha-ninja** [comment]
Hm. I'll make a PR later.
