### ISSUE TITLE
Run an experiment over a few weeks regarding simplification.

### ISSUE THREAD

**Issue by alpha-ninja** [raptor2101/Mediathek#47]
In the ideal scenario, there should be ARD, ZDF, ~~3sat~~, Arte, ~~Phoenix~~, KiKA+, and ORF entries.

To get there, we need to make sure:

-    All NDR programming is also available via the ARD Mediathek (this way we will be able to remove NDR altogether as a separate mediathek)
-    Get Phoenix implemented again.

~~I'll look into Phoenix.~~ Could you write a script that checks whether there are any NDR shows that are not on ARD? Ideally, just dump episode names and check which ones are in NDR but not in ARD. Then, add a switch to enable/disable NDR in the addon settings. (do this over a few weeks to verify that this is actually the case.)

Edit: Phoenix's mediathek seems to be gone.
3sat seems to be included in the ZDF mediathek. (this would also need a script to check over multiple weeks)

**Comment by raptor2101** [comment]
Even if every NDR Mediafile is part of the ARD Mediathek, the ARD Mediathek is badly sorted. Personaly I use the 3sat mediathek quite often (instead of ZDF) because most "kabarett" Related stuff is only available in 3Sat (or better findable)

**Comment by alpha-ninja** [comment]
Ok, thanks.
