### ISSUE TITLE
Add ARD Search, Dossiers

### ISSUE THREAD

**Issue by alpha-ninja** [raptor2101/Mediathek#48]
Sorry for opening so many issues, but I don't have the means to test most of this so I'm posting the changes for you.

For Dossiers:
    TreeNode("X","Dossiers",self.rootLink+"/tv/Dossiers/mehr?documentId=21301810",True)

With searches, the syntax is:
    /tv/suche?searchText=tatort&source=tv (without source=tv, radio is included)

I'm not sure how you'd have to parse the search results, but they include:
-   Series name (where applicable)
-   Episode name
-   Length, date posted, station (in a string separated by " | ")
-   Description

**Comment by raptor2101** [comment]
I will process on issue at a time. currently i'am a little bit bussy cause of my job and "relocation of home"
can take a whil till i fix all

**Comment by alpha-ninja** [comment]
OK, thanks :)
