### ISSUE TITLE
ARTE – Add ability to switch between german/french audio track

### ISSUE THREAD

**Issue by markus-okur** [raptor2101/Mediathek#50]

**Comment by norbertroamsys** [comment]
Ich  habe das analoge Problem mit Version 0.6.4 unter Raspberry. Vielleicht ist es aber auch eine Einstellungssache?!
Auf alle Fälle habe unter Video-Einstellungen als bevorzugte Streamingsprache _German_ angegeben.
Leider werden die Beiträge grundsätzlich in französisch gestreamt.

Danke für einen Tipp oder einen Fix!

**Comment by taleteller** [comment]
Über das Problem bin ich auch gerade gestolpert. Scheinbar ist das mit dem letzten Commit 5bb37f6785a61a7e59690d7850092c2007767183 behoben worden. Der scheint aber noch nicht ins Update eingeflossen, meine 0.6.5 hat ihn jedenfalls nicht.

Ich habe mir händisch mit einer Anpassung des regulären Ausdrucks in Zeile 98 der arte.py geholfen. Praktikabler dürfte es sein die lokale Version davon mit der [korrigierten](https://raw.githubusercontent.com/raptor2101/Mediathek/master/mediathek/arte.py), hier aus dem Repo zu ersetzen. Oder halt auf die 0.6.6 zu warten.

**Comment by raptor2101** [comment]
new version 0.6.5 is released and containing this commit, can you check if the problem still encounters...

**Comment by norbertroamsys** [comment]
To my surprise version 0.6.6 has also been released and installed on my kodi. 

I tried a movie on ARTE yesterday evening an seems to work.
So thanks a lot!
