### ISSUE TITLE
ARD: Can't open "Heiter bis Tödlich."

### ISSUE THREAD

**Issue by alpha-ninja** [raptor2101/Mediathek#53]
Log file had:

    15:03:05 T:139759066261248  NOTICE: Thread JobWorker start, auto delete: true
    15:03:05 T:139758227351296  NOTICE: Thread LanguageInvoker start, auto delete: false
    15:03:05 T:139758227351296  NOTICE: -->Python Interpreter Initialized<--
    15:03:05 T:139758227351296  NOTICE: [Mediathek]: quality: 3
    15:03:05 T:139758227351296  NOTICE: get_params() argv=
    15:03:05 T:139758227351296  NOTICE: ['plugin://plugin.video.mediathek/', '31', '?action=openTopicPage&link=http%3a%2f%2fwww.ardmediathek.de%2ftv%2fHeiter-bis-t%25C3%25B6dlich%2fSendung%3fdocumentId%3d8528326%26amp%3bbcastId%3d8528326&type=ARD']
    15:03:05 T:139758227351296  NOTICE: [Mediathek]: Quality: 3
    15:03:05 T:139758227351296  NOTICE: [Mediathek]: argv[0]: plugin://plugin.video.mediathek/
    15:03:05 T:139758227351296  NOTICE: [Mediathek]: argv[1]: 31
    15:03:05 T:139758227351296  NOTICE: [Mediathek]: http://www.ardmediathek.de/tv/Heiter-bis-t%C3%B6dlich/Sendung?documentId=8528326&amp;bcastId=8528326
    15:03:05 T:139758227351296  NOTICE: [Mediathek]: Build Page Menu: http://www.ardmediathek.de/tv/Heiter-bis-t%C3%B6dlich/Sendung?documentId=8528326&amp;bcastId=8528326 SubLink: 0
    15:03:05 T:139758227351296  NOTICE: [Mediathek]: download http://www.ardmediathek.de/tv/Heiter-bis-t%C3%B6dlich/Sendung?documentId=8528326&bcastId=8528326 0
    15:03:05 T:139758227351296  NOTICE: [Mediathek]: VideoLink: http://www.ardmediathek.de/play/media/26447264?devicetype=pc&feature=flash
    15:03:05 T:139758227351296  NOTICE: [Mediathek]: download http://www.ardmediathek.de/play/media/26447264?devicetype=pc&feature=flash 0
    15:03:05 T:139758227351296  NOTICE: [Mediathek]: 11.02.2015 | 18:50 Uhr
    15:03:05 T:139758227351296  NOTICE: [Mediathek]: URL:http://mvideos.daserste.de/videoportal/Film/c_500000/500493/format597167.mp4
    15:03:05 T:139758227351296  NOTICE: [Mediathek]: VideoLink: http://www.ardmediathek.de/play/media/26290010?devicetype=pc&feature=flash
    15:03:05 T:139758227351296  NOTICE: [Mediathek]: download http://www.ardmediathek.de/play/media/26290010?devicetype=pc&feature=flash 0
    15:03:05 T:139758227351296   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.mediathek/default.py", line 76, in <module>
                                                mediathek.buildPageMenu(link, 0);
                                              File "/storage/.kodi/addons/plugin.video.mediathek/mediathek/ard.py", line 94, in buildPageMenu
                                                elementCount = self.extractElements(mainPage);
                                              File "/storage/.kodi/addons/plugin.video.mediathek/mediathek/ard.py", line 130, in extractElements
                                                self.decodeVideoInformation(videoId, title, subTitle, counter);
                                              File "/storage/.kodi/addons/plugin.video.mediathek/mediathek/ard.py", line 150, in decodeVideoInformation
                                                picture = self.rootLink+self.regex_pictureLink.search(videoPage).group(1);
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
    15:03:05 T:139759612209024   ERROR: GetDirectory - Error getting plugin://plugin.video.mediathek/?action=openTopicPage&link=http%3a%2f%2fwww.ardmediathek.de%2ftv%2fHeiter-bis-t%25C3%25B6dlich%2fSendung%3fdocumentId%3d8528326%26amp%3bbcastId%3d8528326&type=ARD
    15:03:05 T:139759612209024   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mediathek/?action=openTopicPage&link=http%3a%2f%2fwww.ardmediathek.de%2ftv%2fHeiter-bis-t%25C3%25B6dlich%2fSendung%3fdocumentId%3d8528326%26amp%3bbcastId%3d8528326&type=ARD) failed
    15:03:05 T:139758227351296  NOTICE: Thread LanguageInvoker start, auto delete: false
    15:03:05 T:139758227351296  NOTICE: -->Python Interpreter Initialized<--
    15:03:05 T:139758227351296  NOTICE: [Mediathek]: quality: 3
    15:03:05 T:139758227351296  NOTICE: get_params() argv=
    15:03:05 T:139758227351296  NOTICE: ['plugin://plugin.video.mediathek/', '32', '?action=openMenu&path=1.8&type=ARD']
    15:03:05 T:139758227351296  NOTICE: [Mediathek]: Quality: 3
    15:03:05 T:139758227351296  NOTICE: [Mediathek]: argv[0]: plugin://plugin.video.mediathek/
    15:03:05 T:139758227351296  NOTICE: [Mediathek]: argv[1]: 32
    15:03:05 T:139758227351296  NOTICE: [Mediathek]: H
    15:03:05 T:139758227351296  NOTICE: [Mediathek]: Build Page Menu: http://www.ardmediathek.de/tv/sendungen-a-z?buchstabe=H SubLink: 0
    15:03:05 T:139758227351296  NOTICE: [Mediathek]: download http://www.ardmediathek.de/tv/sendungen-a-z?buchstabe=H 0
    15:03:05 T:139758479066880  NOTICE: Thread BackgroundLoader start, auto delete: false

**Comment by alpha-ninja** [comment]
This problem no longer occurs, but it would probably be good if you would look into this.

**Comment by raptor2101** [comment]
As already written, i'am currently ander heavy load and unable to maintain this plugin for at least the next few weeks

hopefully in april i will able to cleanup all reported errors...

**Comment by steffen234** [comment]
i got the same problem. Our intention is to see "Tatort". 
The movie starts ...but not before it is at the end in live tv. I suppose that the movie is moved in the backend (or other changes), so kodi is able to play. 
I am wondering a little bit, because if you go in the log an pick the link e.g. vlc-player is able to play. But this player has other problems to play reliable on our system :-/
Because the "Mediathek" is a great Addon - I'm very curious about hints or solutions. ;) thx

**Comment by steffen234** [comment]
the issue was observed under Windows and Ubuntu... (probably platform independent)
