### ISSUE TITLE
Arte Ansicht fehlerhaft

### ISSUE THREAD

**Issue by theincogtion** [raptor2101/Mediathek#55]
Ih habe Version 0.6.5 und wenn ich auf die Arte Mediathek zugreifen möchte sieht es recht düster aus.
Zur Auswahl bekomme ich nur:

Neueste Videos
Programme 
Themen

Es gibt keine Suche. Über die globale Suche finde ich gar nichts was in der Arte Mediathek ist.
Wenn ich "Neueste Videos" wähle dann arbeitet er eine Zeitlang und dann kommt ein script Fehler.

**Comment by github-user-1** [comment]
Ich habe auch 0.6.5 installiert und bei Arte kommen zwar einige der Sendungen, aber bei weitem nicht alle, die prinzipiell verfügbar wären. Z. Bsp. wenn ich über "Programme" -> "Arte Journal" gehe, bekomme ich nur eine leere Liste (obwohl es die letzten Arte-Journal-Sendungen in der Mediathek gibt). Es scheint also in der Tat etwas nicht ganz rund zu laufen...

**Comment by raptor2101** [comment]
die Suche ist noch nicht implementiert, das stimmt. kannst du mir ein debug-log mit dem scrtipt fehler schicken.

das mit dem Arte journal schau ich mir gerade an ...

**Comment by raptor2101** [comment]
@github-user-1 kannst du bei dir mal die neue arte.py ausprobieren und prüfen ob arte journal bei dir funktioniert?

**Comment by theincogtion** [comment]
Schön von dir zu hören Raptor2101!
Gerne schicke ich dir das wenn du mir sagst wo das liegt bzw wo ich es aktivieren kann

**Comment by raptor2101** [comment]
Das ganze liegt im Kodi User Ordner unter temp. Unter linux findest du es so: .kodi/temp/kodi.log

**Comment by Wikinaut** [comment]
Bei mir geht das Mediathek/Arte auch nicht. (Das spezielle Arte+7 AddOn geht aber.)

**Comment by raptor2101** [comment]
jup mitlerweile habe sie ihr interface komplett umgebaut ... ich muss es readaptieren...

**Comment by Wikinaut** [comment]
@raptor2101 ich bitte darum. Wenn fertig, sende ich Dir eine kleine Donation.

**Comment by raptor2101** [comment]
bin gerade drann, schaut nicht so kompliziert aus ... donation brauch ich nicht ;)

**Comment by raptor2101** [comment]
hab die arte.py mal notdürftig geflickt. arte+7 läd wieder, jetzt ist der feinschliff drann ....

**Comment by Wikinaut** [comment]
@raptor2101 do you have an idea, when (how) this will become available as an AddOn-update on OSMC ?

**Comment by raptor2101** [comment]
If OSMC using a "plain" Kodi (or dont touch the addon repos) the update should be installed automaticaly 

i will push this change during the next week (have to fix KiKa and ZDF also ...)

**Comment by Wikinaut** [comment]
@raptor2101 @XaverW Hi, some days ago I filed a different but similar idea with MediathekView : https://github.com/xaverW/MediathekView/issues/60 .

Perhaps - I don't know, but want to let me know my idea of this morning - it would be easily possible to **add** the (offline) data ("Filmliste" of ~70-90.000 available movies) of MediathekView every day to your Mediathek Addon, as a kind of "pseudo TV station" (additional entry in your Addon station list), from which your AddOn could quickly fetch the Url of a movie, without the need to go to the "station X Mediathek".


Do you understand what I mean ? Add MediathekView's list as new entry. Should be easy, and perhaps you can and want to cooperate with @XaverW .

Perhaps the collection of conversion scripts https://github.com/Skeeve/Mediathek-3.3-Filmliste/blob/master/filmliste_laden is an easy starting point, or https://sourceforge.net/p/zdfmediathk/wiki/FAQ/#filmliste-wird-nicht-vollstandig-geladen .

**Comment by Wikinaut** [comment]
Here's an edited excerpt of the Filmliste:

```
{
  "Filmliste" : [ "25.01.2016, 16:19", "25.01.2016, 15:19", "3", "MSearch [Rel: 516] - Compiled: 21.01.2016 / 18:28:22", "874e30dca266b1fe704bc4cb728f1c66" ],
  "Filmliste" : [ "Sender", "Thema", "Titel", "Datum", "Zeit", "Dauer", "Größe [MB]", "Beschreibung", "Url", "Website", "Untertitel", "UrlRTMP", "Url_Klein", "UrlRTMP_Klein", "Url_HD", "UrlRTMP_HD", "DatumL", "Url_History", "Geo", "neu" ],
  "X" : [ "3Sat", "3sat", "Eisige Welten (3/5)", "25.01.2016", "21:40:00", "00:43:06", "762", "Es ist Sommer. Ein einziger Tag erstreckt sich über Wochen, bis zu sechs Monaten! Kaum vorstellbar, aber die Sonne geht nicht mehr unter. Im gleißenden Licht des Polartages schmilzt den Eisbären...", "http://nrodl.zdf.de/dach/3sat/15/01/150118_eisige_welten3_online_2256k_p14v11.mp4", "http://www.3sat.de/mediathek/?mode=play&obj=48754", "", "", "65|436k_p9v11.mp4", "", "", "", "1453754400", "", "DE-AT-CH", "true" ],
  "X" : [ "", "", "Population Boom © ORF/www.austrianfilm.at/Geyrhalter Film", "24.01.2016", "21:45:00", "01:29:11", "1563", "Der preisgekrönte österreichische Regisseur Werner Boote (\"Plastic Planet\") bereist für seinen Dokumentarfilm unsere Erde, die mit sieben Milliarden Menschen bereits überbevölkert ist....", "http://nrodl.zdf.de/dach/3sat/16/01/160124_population_boom_online_2328k_p35v12.mp4", "http://www.3sat.de/mediathek/?mode=play&obj=56521", "", "", "66|436k_p9v12.mp4", "", "66|3328k_p36v12.mp4", "", "1453668300", "", "DE-AT-CH", "false" ],
  "X" : [ "", "", "Eisige Welten (2/5)", "25.01.2016", "21:00:00", "00:43:09", "763", "Beginnend mit der großen Schmelze im Frühling steht die zweite Folge ganz im Licht der zurückkehrenden Sonne. Ihre Wärme verwandelt die magische Eiswelt nach einem halben Jahr Dunkelheit. Noch...", "http://nrodl.zdf.de/dach/3sat/15/01/150111_eisige_welten2_online_2256k_p14v11.mp4", "http://www.3sat.de/mediathek/?mode=play&obj=48700", "", "", "65|436k_p9v11.mp4", "", "", "", "1453752000", "", "DE-AT-CH", "true" ],
  "X" : [ "", "", "Nuhr im Ersten © RBB", "24.01.2016", "21:00:00", "00:45:27", "796", "Scharfzüngig und anspruchsvoll, bissig und hintergründig, unterhaltsam und witzig - Kabarett und Comedy treffen sich bei \"Nuhr im Ersten - Der Satire Gipfel\".", "http://nrodl.zdf.de/none/3sat/16/01/160124_nuhrimersten_ard_2328k_p35v12.mp4", "http://www.3sat.de/mediathek/?mode=play&obj=56550", "", "", "60|436k_p9v12.mp4", "", "60|3328k_p36v12.mp4", "", "1453665600", "", "", "false" ],
  "X" : [ "", "", "Eisige Welten (1/5)", "25.01.2016", "20:15:00", "00:43:09", "762", "Die erste Folge entführt in Arktis und Antarktis und stellt sie als Eis gewordene Superlative vor. Fast 80 Prozent des Süßwassers unseres Planeten sind dort gebunden, Winde peitschen mit 320...", "http://nrodl.zdf.de/dach/3sat/15/01/150111_eisige_welten1_online_2256k_p14v11.mp4", "http://www.3sat.de/mediathek/?mode=play&obj=48699", "", "", "65|436k_p9v11.mp4", "", "", "", "1453749300", "", "DE-AT-CH", "true" ],
    ....
  "X" : [ "", "", "Ausschnitt: Marinas Rettungsmission", "21.10.2015", "16:00:00", "00:02:15", "40", "Marina will die Schildkröteneier in Sicherheit bringen. Dabei trifft sie auf die Gauner Rico und Biff. Was haben die beiden nur vor?", "http://nrodl.zdf.de/none/tivi/15/10/151014_folge2_ausschnitt_zoo_2256k_p14v11.mp4", "http://www.tivi.de/fernsehen/zoom-der-weisse-delfin/start/index.html ", "", "", "", "", "", "", "1445436000", "", "", "false" ]
}
```
