### ISSUE TITLE
Mediathek

### ISSUE THREAD

**Issue by bomber-harris** [raptor2101/Mediathek#56]
Hallo, 

ich habe gerade versucht - aufgrund der fehlerhaften Ansicht der ArteMediathek - die Datei über Raspbian in das entsprechende Kodi Verzeichnis einzubinden. 
Nun funktionierte das auch, allerdings ergab sich folgendes Problem. 
Beim Starten von Kodi und dem Öffnen des Video-Addons zeigte mir Kodi, dass ein Skript-Fehler vorliegt. 
Was habe ich falsch gemacht, bzw. wie kann ich die von ihnen verbesserte arte.py in Kodi einbinden? 

Zweite Frage: 

Ließe sich auch irgendwie Arte7+ und der Arte-Livestream in das entsprechende Addon einbinden? 

Danke schon mal!

**Comment by raptor2101** [comment]
kannst du mir den scriptfehler senden (kodi.log)

**Comment by Mangnoppa** [comment]
Da dies **das** Add-On ist was ich benutze und auf eine Lösung hoffe, hier der Auszug aus meinem Log
```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
         - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
        Error Type: <type 'exceptions.ImportError'>
        Error Contents: No module named lxml.html
        Traceback (most recent call last):
          File "/storage/.kodi/addons/plugin.video.mediathek/default.py", line 21, in <module>
            from mediathek.factory import MediathekFactory
          File "/storage/.kodi/addons/plugin.video.mediathek/mediathek/factory.py", line 27, in <module>
            from mediathek.kika import *
          File "/storage/.kodi/addons/plugin.video.mediathek/mediathek/kika.py", line 19, in <module>
            import lxml.html
        ImportError: No module named lxml.html
        -->End of Python script error report<--
ERROR: GetDirectory - Error getting plugin://plugin.video.mediathek/
ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mediathek/) failed
```
Nebenbei sagt der Update-Manager auch `Abhängigkeiten nicht erfüllt`
OpenELEC (official) - Version: 6.0.3 auf einem Rapsberry Pi 1

**Comment by raptor2101** [comment]
Dein Post hat nur nix mit dem Bug zu tun ...

Dein Problem ist schon gelöst und ich warte darauf, das mein PR aktzeptiert wird. Siehe: https://github.com/xbmc/repo-plugins/pull/619
