### ISSUE TITLE
NDR Suche und verpasste Sendungen gehen nicht

### ISSUE THREAD

**Issue by mcflay0106** [raptor2101/Mediathek#60]
Hallo Raptor2101,
leider gibt es zwei Probleme mit der NDR.py .

Die Suche zeigt keine Ergebnise an.
Wenn ich es richtig sehe scheint Dein Such-Link nicht zu stimmen
Dein Link
 http://www.ndr.de/mediathek/mediatheksuche101.html?pagenumber=1&search_video=true&query=baltrum
NDR Link
http://www.ndr.de/suche10.html?query=baltrum&search_mediathek=1

Und bei Sendung verpasst gibt es einen Scriptfehler:
09:15:06 T:2552  NOTICE: ['plugin://plugin.video.mediathek/', '5', '?action=openMenu&path=1&type=NDR']
09:15:06 T:2552  NOTICE: [Mediathek]: Quality: 2
09:15:06 T:2552  NOTICE: [Mediathek]: argv[0]: plugin://plugin.video.mediathek/
09:15:06 T:2552  NOTICE: [Mediathek]: argv[1]: 5
09:15:06 T:2552  NOTICE: [Mediathek]: download http://www.ndr.de/mediathek/sendungen_a-z/index.html 0
09:15:06 T:2552  NOTICE: [Mediathek]: Sendung verpasst?
09:15:06 T:2552  NOTICE: [Mediathek]: download http://www.ndr.de/mediathek/dropdown105-extapponly.html 0
09:15:07 T:2552  NOTICE: [Mediathek]: download http://www.ndr.de/mediathek/dropdown105-extapponly.html 1
09:15:09 T:2552  NOTICE: [Mediathek]: download http://www.ndr.de/mediathek/dropdown105-extapponly.html 2
09:15:14 T:2552  NOTICE: [Mediathek]: download http://www.ndr.de/mediathek/dropdown105-extapponly.html 4
09:15:22 T:2552  NOTICE: [Mediathek]: download http://www.ndr.de/mediathek/dropdown105-extapponly.html 8
09:15:38 T:2552  NOTICE: [Mediathek]: download http://www.ndr.de/mediathek/dropdown105-extapponly.html 16
09:16:10 T:2552  NOTICE: [Mediathek]: download http://www.ndr.de/mediathek/dropdown105-extapponly.html 32
09:16:10 T:2552   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "C:\Users\mcflay\AppData\Roaming\Kodi\addons\plugin.video.mediathek\default.py", line 84, in <module>
                                                mediathek.buildMenu(path)
                                              File "C:\Users\mcflay\AppData\Roaming\Kodi\addons\plugin.video.mediathek\mediathek__init__.py", line 107, in buildMenu
                                                self.buildMenu(path,treeNode);
                                              File "C:\Users\mcflay\AppData\Roaming\Kodi\addons\plugin.video.mediathek\mediathek__init__.py", line 115, in buildMenu
                                                self.buildPageMenu(treeNode.link,len(treeNode.childNodes));
                                              File "C:\Users\mcflay\AppData\Roaming\Kodi\addons\plugin.video.mediathek\mediathek\ndr.py", line 195, in buildPageMenu
                                                self.buildPageMenuSendungVerpasst(link[15:])
                                              File "C:\Users\mcflay\AppData\Roaming\Kodi\addons\plugin.video.mediathek\mediathek\ndr.py", line 64, in buildPageMenuSendungVerpasst
                                                verpasstNow = regex_verpasstNow.search(htmlPage).group(1);
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
09:16:11 T:3696   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.mediathek/?action=openMenu&path=1&type=NDR
09:16:11 T:3696   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mediathek/?action=openMenu&path=1&type=NDR) failed
09:16:11 T:4544  NOTICE: Thread BackgroundLoader start, auto delete: false

Auch hier scheinen sich die Link-Adressen geändert zu haben.
Hoffe Du bekommst das wieder zum laufen :-)

**Comment by raphaj** [comment]
Auch die Sendung A-Z gingen nicht mehr.
Habe alles gefixt und einen Pull Request erstellt. https://github.com/raptor2101/Mediathek/pull/62
Livestreaming habe ich wieder hinzugefügt, da es bei mir ohne zu ruckeln läuft.

Viel Spaß beim Schauen.

**Comment by azrdev** [comment]
#62 was merged, can close this issue?
