### ISSUE TITLE
OpenElec/Kodi 14.2: Plugin Mediathek als defekt markiert

### ISSUE THREAD

**Issue by h1618** [raptor2101/Mediathek#61]
OpenElec warnt seit kurzem, dass das Mediathek-Plugin nicht kompatibel sei und man es deaktivieren solle. In der Plugin-Beschreibung kommt der Hinweis, dass man auf Kodi 14 upgraden soll (14.2 läuft!), das Plugin funktioniert aber nach wie vor. Es sieht so aus, als ob jemand das Plugin *für ältere Kodi-Versionen* als inkompatibel markieren wollte, das aber generell für alle gemacht hat.

**Comment by raptor2101** [comment]
Kann ich bestätigen sogar mit Isengard (v15) kommt die meldung. Ich meld mich beim maintainer...
