### ISSUE TITLE
ZDF/Logo. Open - error probing input format, http://fstreaming.zdf.de/zdf/300/15/11/151104_mi_lot.smil

### ISSUE THREAD

**Issue by dns42** [raptor2101/Mediathek#64]
Gruesse aus Vancouver, BC. Meine zweijaehrige geht seit 2 Tagen
nicht mehr freiwillig ins Bett, weil LogoTV aufgegeben hat zu laden. Das ist neu.

Mediathek is 0.6.9, OpenElec 5.0.8 auf einer CuBox:
Kodi (14.2 Git:7cc53a9). Platform: Linux ARM 32-bit

Mitschnitte anbei. Hth?

Thx,
Daniel

--snip--
21:18:31 T:1968984064  NOTICE: DVDPlayer: Opening: http://fstreaming.zdf.de/zdf/300/15/11/151104_mi_lot.smil
21:18:31 T:1968984064 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
21:18:31 T:1527772224  NOTICE: Thread DVDPlayer start, auto delete: false
21:18:31 T:1527772224  NOTICE: Creating InputStream
21:18:31 T:1647789120  NOTICE: Thread FileCache start, auto delete: false
21:18:31 T:1527772224  NOTICE: Creating Demuxer
21:18:31 T:1527772224   ERROR: Open - error probing input format, http://fstreaming.zdf.de/zdf/300/15/11/151104_mi_lot.smil
21:18:31 T:1527772224   ERROR: OpenDemuxStream - Error creating demuxer
21:18:31 T:1527772224  NOTICE: CDVDPlayer::OnExit()
21:18:31 T:1968984064   ERROR: Playlist Player: skipping unplayable item: 0, path [http://fstreaming.zdf.de/zdf/300/15/11/151104_mi_lot.smil]
21:18:31 T:1968984064  NOTICE: CDVDPlayer::CloseFile()
21:18:31 T:1968984064  NOTICE: DVDPlayer: waiting for threads to exit
--snip--

**Comment by raptor2101** [comment]
Habs mir mal angeschaut. Ich kann bei mir den Fehler nicht nachstellen. Kannst du mir mal einen kompletten Logmitschnitt geben, dass ich sehe wo er sich den Link zu dem SMIL File herholt.

BTW ich hab getestet mit StreamType RTMP und Quality High

Grüße nach Vancouver

**Comment by dollydl** [comment]
Ich kann das Problem bestätigen. Seit ca. 1 Woche sind es keine MP4-Dateien mehr, wenn man StreamType RTMP und Quality HD gewählt hat, mit der Qualitätseinstellungen Hoch gibt es kein Problem.

Sind jetzt "smil" Dateien, habe aber keine Ahnung ob es nur an Linux liegt, weil z.B. eine Lib fehlt

Mediathek 0.6.9, Kodi 15.2 unter (L)Ubuntu LTS 14.04.3

Grüße
Uwe

**Comment by raptor2101** [comment]
Stellt mal auf Stream Type HTTP, als quick workaround. Die SMIL Datei muss ich erst noch laden/parsen und daraus wieder den RTMP Link erraten ...
