### ISSUE TITLE
Integrate with library

### ISSUE THREAD

**Issue by Crissov** [raptor2101/Mediathek#69]
Would it be possible to add (repeating) shows to the library? So you would only use the addon to select series you want to watch regularly (_subscribe_) and can later access them transparently in the default way.

You can setup Kodi to index, for instance, Genesis or 1Channel addon folders (`special://profile/addon_data/plugin.video.…`) where they store [.strm](http://kodi.wiki/view/STRM) files. Their entries then will appear in standard TV and Movies folders in the GUI, with cover, info etc. if some scraper knew about the show or film.

**Comment by raptor2101** [comment]
will take a look into this
