### ISSUE TITLE
ARD Sendungsliste (0-9,A-Z) and Subfolder stopped working

### ISSUE THREAD

**Issue by marksml** [raptor2101/Mediathek#70]
As of Tuesday 23.02.2016 the plugin stopped working properly for the ARD Mediathek. Seems they changed the structure of the links. bcastId comes now first and only then the documentId. I changed it, but there seem to be more issues. Would most likely faster if someone looks at the code and the new webpage design who knows the plugins code.

Would be great if it can be fixed in time.

Thanks & Cheers, Michael

**Comment by raptor2101** [comment]
there you go ... weekend ;)

**Comment by marksml** [comment]
I am looking into it already. If I have something running before you find time to look into it I will send you a pull request. 

Cheers from Greifensee, CH

**Comment by raptor2101** [comment]
Goto line 68 and replace:
    self.regex_VideoPageLink = re.compile("<a href=\".*Video\?bcastId=\d+&amp;documentId=(\d+)\" class=\"textLink\">\s+?<p class=\"dachzeile\">(.*?)</p>\s+?<h4 class=\"headline\">(.*?)</h4>")
    self.regex_CategoryPageLink = re.compile("<a href=\"(.*Sendung\?bcastId=\d+&amp;documentId=\d+)\" class=\"textLink\">\s+?<p class=\"dachzeile\">.*?</p>\s+?<h4 class=\"headline\">(.*?)</h4>\s+?<p class=\"subtitle\">(.*?)</p>")

**Comment by marksml** [comment]
Thanks for the hint. I had reversed "bcastId=\d+&amp;documentId=(\d+)" but had kept the (\d+) with bcastId. It is working with let's say Highlights now, but if I try to dive in one of the letters it doesn't find any links and as consequence doesn't show anything. Might a local bug in my code. I will get a fresh copy and start over. Thanks & Regards

**Comment by raptor2101** [comment]
confirm, subsection "A-Z" doesn't work with that fix either...

**Comment by marksml** [comment]
wait it works, if you only do the change for line 68 (self.regex_VideoPageLink only)

self.regex_VideoPageLink = re.compile("<a href=\".*Video\?bcastId=\d+&amp;documentId=(\d+)\" class=\"textLink\">\s+?<p class=\"dachzeile\">(.*?)</p>\s+?<h4 class=\"headline\">(.*?)</h4>")

leave the cataoryPageLink pattern as is with regard to sequence of documentId and bcastId

It works for me now.

Thanks & Regards

**Comment by raptor2101** [comment]
try this:

```
self.regex_VideoPageLink = re.compile("<a href=\".*Video\?.*?documentId=(\d+).*?\" class=\"textLink\">\s+?<p class=\"dachzeile\">(.*?)</p>\s+?<h4 class=\"headline\">(.*?)</h4>")
    self.regex_CategoryPageLink = re.compile("<a href=\"(.*Sendung\?.*?documentId=\d+.*?)\" class=\"textLink\">\s+?<p class=\"dachzeile\">.*?</p>\s+?<h4 class=\"headline\">(.*?)</h4>\s+?<p class=\"subtitle\">(.*?)</p>")
```

**Comment by xhaggi** [comment]
works thanks

**Comment by marksml** [comment]
Thank you very mich indeed. Have a nice weekend! Cheers

**Comment by marksml** [comment]
Confirmed. Thank you very mich indeed. Have a nice weekend! Cheers

**Comment by gammapower** [comment]
Could someone describe the solution a little bit more in detail. I'm new to this and I don't know where I should change it.

Thank you very much!

**Comment by raptor2101** [comment]
You should have nothing to do. I pushed this change into the public repo and it was released fews days ago ... it should work out of the box
