### ISSUE TITLE
Live streams in HD only

### ISSUE THREAD

**Issue by Matthias84** [raptor2101/Mediathek#71]
Hi, I enjoy this addon very much, so thanks for maintaining and developing this piece of code :smiley: 

Unfortunatly, there seems to be an small problem with the Live videostreams, as they don't switch back to SD or low quality. For my low bandwith connection HD is impossible and the stream pauses as the cache is empty:

> 13:13:37 T:2100 WARNING: CDVDMessageQueue(audio)::Get - asked for new data packet, with nothing available
> 13:13:37 T:2100  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21

For example, if I setup Mediathek to use low quality and HTTP stream, it persists using HD streams with 1280x720 for NDR live:  

> ..
> 13:14:24 T:4500  NOTICE: [Mediathek]: download http://www.ndr.de/mediathek/sendungen_a-z/index.html 0
> 13:14:24 T:4500  NOTICE: [Mediathek]: Live
> 13:14:24 T:4500  NOTICE: [Mediathek]: Hamburg
> 13:14:24 T:4500  NOTICE: [Mediathek]: URL:http://ndr_fs-lh.akamaihd.net/i/ndrfs_hh@119223/master.m3u8
> 13:14:24 T:4500  NOTICE: [Mediathek]: Mecklenburg-Vorpommern
> 13:14:24 T:4500  NOTICE: [Mediathek]: URL:http://ndr_fs-lh.akamaihd.net/i/ndrfs_mv@119226/master.m3u8
> 13:14:24 T:4500  NOTICE: [Mediathek]: Niedersachsen
> 13:14:24 T:4500  NOTICE: [Mediathek]: URL:http://ndr_fs-lh.akamaihd.net/i/ndrfs_nds@119224/master.m3u8
> 13:14:24 T:4500  NOTICE: [Mediathek]: Schleswig-Holstein
> 13:14:24 T:4500  NOTICE: [Mediathek]: URL:http://ndr_fs-lh.akamaihd.net/i/ndrfs_sh@119225/master.m3u8
> 13:14:41 T:4276  NOTICE: DVDPlayer: Opening: http://ndr_fs-lh.akamaihd.net/i/ndrfs_mv@119226/master.m3u8
> 13:14:41 T:4276 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
> 13:14:41 T:3420  NOTICE: Creating InputStream
> 13:14:41 T:3420  NOTICE: Creating Demuxer
> ...

My setup is:
- Mediathek 0.7.1
- Kodi 16.0 Jarvis
- OS Windows 7 (32bit)

If there is anything where I can help to reproduce the bug, just send me an ping.

**Comment by raptor2101** [comment]
Sorry for my late answer, for some reasons i missed this issue

These Streams should be "auto-negotiate" the possible bandwidth. I will look if NDR over some low-bandwith links, but i won't bet on it ...
