### ISSUE TITLE
Support for subtitles

### ISSUE THREAD

**Issue by comick** [raptor2101/Mediathek#73]
Most of sources also provide subtitles in form of xml files.
As an example ZDF XML service "http://www.zdf.de/ZDFmediathek/xmlservice/web/beitragsDetails?id=%s&ak=web" response contains the url to XML subtitles in the element at path /response/video/caption/url.

Example: http://www.zdf.de/ZDFmediathek/xmlservice/v2/web/beitragsDetails?ak=web&id=2705994
Contains:

``` xml
...
<caption>
  <url>https://utstreaming.zdf.de/tt/2016/F1006830_deut_Katie_fforde_Hexensommer_010516.xml</url>
  <offset>0</offset>
</caption>
...
```

Is there any issue preventing subtitles integration into this addon?

**Comment by comick** [comment]
Das Erste also has subtitles.
As an examples, resrouce http://mediathek.daserste.de/play/media/34922508?devicetype=pc&features=flash

mention the subtitle resource in field `$._subtitleUrl` http://mediathek.daserste.de/subtitle/56906

**Comment by raptor2101** [comment]
there is no issue known to me. as soon as i have time, i will look into this ...(during this week)

**Comment by raptor2101** [comment]
After a long time of silence: Do you look at the other Plugins "ZDF Mediathek" and "ARD MEdiathek"?They already implemented the subtitles.
