### ISSUE TITLE
ARTE broken

### ISSUE THREAD

**Issue by ebora** [raptor2101/Mediathek#86]
ARTE stopped working some days ago. Seems they changed something on their website like ZDF did.

kodi.log output:

20:26:38 1984.299561 T:2674107376  NOTICE: [Mediathek]: quality: 2
20:26:38 1984.301880 T:2674107376  NOTICE: [Mediathek]: Quality: 2
20:26:38 1984.303467 T:2674107376  NOTICE: [Mediathek]: argv[0]: plugin://plugin.video.mediathek/
20:26:38 1984.305176 T:2674107376  NOTICE: [Mediathek]: argv[1]: 13
20:26:38 1984.405396 T:2674107376  NOTICE: [Mediathek]: Arte+7
20:26:58 2004.212769 T:2674107376  NOTICE: [Mediathek]: quality: 2
20:26:58 2004.215210 T:2674107376  NOTICE: [Mediathek]: Quality: 2
20:26:58 2004.216797 T:2674107376  NOTICE: [Mediathek]: argv[0]: plugin://plugin.video.mediathek/
20:26:58 2004.218262 T:2674107376  NOTICE: [Mediathek]: argv[1]: 14
20:26:58 2004.311890 T:2674107376  NOTICE: [Mediathek]: Alle Videos
20:26:58 2004.313599 T:2674107376  NOTICE: [Mediathek]: buildPageMenu: http://www.arte.tv/guide/de/plus7
20:26:58 2004.328613 T:2674107376  NOTICE: [Mediathek]: download http://www.arte.tv/guide/de/plus7 0
20:26:58 2004.725586 T:2674107376  NOTICE: [Mediathek]: Found 0 unique links

**Comment by raptor2101** [comment]
Nice one ... seems i have to do some work ... and this at the same day Deus Ex is released for linux ^^

**Comment by raptor2101** [comment]
Can anyone give a first try ?

**Comment by ElmarSieke** [comment]
It works partly.

menu "Alle Videos"
1) The list isn't complete.
2) The order is wrong (part 2/6, part 6/6 ...).

In other menus I saw the same behavior.

**Comment by ebora** [comment]
On Linux pi 4.4.27-2-osmc it seems to work fine, except for the sort order mentioned above.
I don't know how to check wether the list is complete, though.

**Comment by raptor2101** [comment]
The ordering problem is caused by the way how the plugin fetching the VideoLinks, This is an "old"  problem. The missing Videos are caused by a change in the hirarchy. 

I will push this as it is to Kodi Upstream and will switch the algorithm "how to extract the videos" from a simple "regex" approach to a "parse html" approach (like done for the kika plugin)

**Comment by raptor2101** [comment]
Fix released please test

**Comment by ebora** [comment]
During a quick first test I noticed the following:
- I see the titles of the programs in german (which is what I want) but when I select one, it is played in french, without subtitles.
- selecting "Arte+7" I see: "Most Wanted", "Dailymostviewed", "Expiringvideos" (which are directories with only 3 videos each shown) and several programs (which start playing on click).  This is diffrent than on the webpage: There are shown links to categories with 3 examples each. But the link leads to more videos in that category. Maybe you could expand the contends of the "most wanted" etc. directories by following the link and for the other programs link to the "Kategorien" directory one directory up?
- not all the videos are shown which are on the arte website:
e.g. choose "Sendungen A-Z" - "Xenius". There are several parts in that page with 2 info-videos about the program on top, then the upcomming subjects, then 6 past videos and below that a button "mehr sehen" which leads to a page with more videos. In the Mediathek plugin I am shown 8 videos, 2 are from part 1 of the webpage and 6 are from the last part of the webpage (whithout any distinction between them). Interestingly, the 6 old videos are not the same as those on the website, one is different. But the most important thing here is the missing "next page" in the plugin, we're missing at least 3 additional pages here.
- same with entries in "Kategorien": in the plugin less videos are listed than on the website.
- I miss information about the videos when I scroll down the list - like when was it broadcast and how long is it. Right now only a picture is shown.
- I'd like a search option

I hope my descriptions aren't too confusing...

**Comment by raptor2101** [comment]
I will address some issues with the next release ...

**Comment by raptor2101** [comment]
- [x] I see the titles of the programs in german (which is what I want) but when I select one, it is played in french, without subtitles.
- [x] selecting "Arte+7" I see: "Most Wanted", "Dailymostviewed", "Expiringvideos" (which are directories with only 3 videos each shown) and several programs (which start playing on click). This is diffrent than on the webpage: There are shown links to categories with 3 examples each. But the link leads to more videos in that category. Maybe you could expand the contends of the "most wanted" etc. directories by following the link and for the other programs link to the "Kategorien" directory one directory up?
not all the videos are shown which are on the arte website:
- [ ] e.g. choose "Sendungen A-Z" - "Xenius". There are several parts in that page with 2 info-videos about the program on top, then the upcomming subjects, then 6 past videos and below that a button "mehr sehen" which leads to a page with more videos. In the Mediathek plugin I am shown 8 videos, 2 are from part 1 of the webpage and 6 are from the last part of the webpage (whithout any distinction between them). Interestingly, the 6 old videos are not the same as those on the website, one is different. - [ ] But the most important thing here is the missing "next page" in the plugin, we're missing at least 3 additional pages here.
same with entries in "Kategorien": in the plugin less videos are listed than on the website.
- [ ] I miss information about the videos when I scroll down the list - like when was it broadcast and how long is it. Right now only a picture is shown.
- [ ] I'd like a search option

**Comment by raptor2101** [comment]
ok i fixed four of your five request. 

Cause off the "Subsites" (like Xenius) offers a complete different layout and site-loading, i'am unable to adopt this short handed without blowing up the whole class.

I will lock into this after I get ORF back working ...

**Comment by ebora** [comment]
Great, thank you!! 
The usability is much improved. The remaining issues are minor. 
Workaroud to get more videos of a show than shown in the folders below "Sendungen A-Z": use search function.
