### ISSUE TITLE
Probleme mit 3sat und ZDF

### ISSUE THREAD

**Issue by teK04** [raptor2101/Mediathek#91]
Hallo,

ich nutze die Mediathek hauptsächlich für 3sat "nano" und "Frag den Lesch (ZDF)". Beides kann ich allerdings schon seit einigen Wochen nicht mehr nutzen.

1. Bei 3sat "nano" werden mir immer nur noch 2 oder 3 Einträge angezeigt.
2. Bei "Frag den Lesch" gar nichts mehr (auch andere ZDF-Sendungen nicht).

Keine diesbezüglichen Fehlermeldungen im Log. Kodi auf letzte Stable.

Vielen Dank schon mal für deine Hilfe!

Liebe Grüße,
Thomas

**Comment by raptor2101** [comment]
Komplett ZDF geht mit dem "aktuellen" Plugin nicht. Der entsprechende PR(https://github.com/xbmc/repo-plugins/pull/756) dümpel seit fast 2 Wochen rumm ...

1) schau ich mir die woche an, nachdem ich arte endlich fertig hab ...
