### ISSUE TITLE
Mediathek not available in KODI v15.2

### ISSUE THREAD

**Issue by strollingf** [raptor2101/Mediathek#95]
Hi,
why is the mediathek addon not available in the Kodi v15.x repos anymore?
I would like to run it on my RasPi B+ an tried the acutal versions of OpenELEC and OSMC but none of them lists the addon under "video addons".
When trying to install the .zip manually it says "depenencies not met, please contact author".
Thanks, Felix

**Comment by raptor2101** [comment]
this is in length explained here https://github.com/raptor2101/Mediathek/issues/85
