### ISSUE TITLE
Mediathek doesn't play certain sources

### ISSUE THREAD

**Issue by Kirk1984** [raptor2101/Mediathek#99]
[kodi.log](https://github.com/raptor2101/Mediathek/files/1348702/kodi.log)

Same issue on my Raspberry Pi3 with Libreelec 8.0.x - 8.1.x.

I'm no developer, but i guess the problem are the "//" that are added to the beginning of the url for the Media source.

`ERROR: CVideoPlayer::OpenInputStream - error opening [//wdrmedien-a.akamaihd.net/medp/ondemand/weltweit/fsk0/148/1480607/1480607_16997126.mp4]`

**Comment by raptor2101** [comment]
confirm, i will take a look at this as soon as possible

**Comment by fehmer** [comment]
Hi,

as a workaround i added this in the mediathek/ard.py:

```python
videoLinks = {}
    for match in self.regex_videoLinks.finditer(videoPage):
      quality = int(match.group(1));

      # workaround for links from WDR
      temp = match.group(2);
      if temp.startswith('//'):
        temp = 'http:'+temp;
      link = SimpleLink(temp,0);
     # end workaround
 
      if(quality > 0):
       quality -= 1
```

**Comment by helmutundarnold** [comment]
Thanks for the workaround, now we can see "Die Sendung mit der Maus".
   Best Regards from Helmut and Dave

**Comment by raptor2101** [comment]
sorry for my late answer but i'am was unable to look on the problem till now (we have a very long weekend here ... so time for private programming ;))

i will push these changes as fast as possible to upstream...

**Comment by raptor2101** [comment]
PullRequest is pending: https://github.com/xbmc/repo-plugins/pull/1487

**Comment by raptor2101** [comment]
PullRequest merged
